name: CI
# Controls when the action will run
on: 
  #Triggers the workflow on push or pull request events for master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  #allows you to run this workflow manually from the actions tab
  workflow_dispatch:
#A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    #The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 
      #Check out our code base, it will take this github repo on clone it on that ubuntu machine
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #Once code is checked will run this step
      #Runs a single command using the runners shell
      - name : Run a one-line script
        run: echo Hello, world!
      #Runs a set of commands using the runners shell
      - name : Run a multi-line script
        run: 
            echo Add other actions to build,
            echo test, and deploy your project
      
  
